# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Alex Forsythe, Academy of Motion Picture Arts and Sciences

include_guard(GLOBAL)
include(FetchContent)

set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
# Keep the user package registry out of dependency resolution: never
# register our vendored build trees, never resolve from stale ones.
set(CMAKE_EXPORT_NO_PACKAGE_REGISTRY ON)
set(CMAKE_FIND_USE_PACKAGE_REGISTRY OFF)

# --- Imath / OpenEXR: find-or-fetch ----------------------------------------
# FIND_PACKAGE_ARGS = stock find-or-fetch: an installed package wins; when
# none is found, a pinned static copy builds in-tree. Force the hermetic
# path with -Ccmake.define.FETCHCONTENT_TRY_FIND_PACKAGE_MODE=NEVER.
# OpenEXR pulls its own pinned libdeflate when none is installed.
set(_ctlpy_imath_version   "3.1.11")
set(_ctlpy_openexr_version "3.2.9")

FetchContent_Declare(Imath
    GIT_REPOSITORY https://github.com/AcademySoftwareFoundation/Imath.git
    GIT_TAG        v${_ctlpy_imath_version}
    GIT_SHALLOW    TRUE
    SYSTEM EXCLUDE_FROM_ALL
    FIND_PACKAGE_ARGS 3 CONFIG
)
FetchContent_Declare(OpenEXR
    GIT_REPOSITORY https://github.com/AcademySoftwareFoundation/openexr.git
    GIT_TAG        v${_ctlpy_openexr_version}
    GIT_SHALLOW    TRUE
    SYSTEM EXCLUDE_FROM_ALL
    FIND_PACKAGE_ARGS 3 CONFIG
)
# In-tree-build knobs; inert when installed packages are found.
set(BUILD_TESTING OFF CACHE BOOL "" FORCE)
set(IMATH_INSTALL OFF CACHE BOOL "" FORCE)
set(IMATH_INSTALL_PKG_CONFIG OFF CACHE BOOL "" FORCE)
set(OPENEXR_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(OPENEXR_BUILD_TOOLS OFF CACHE BOOL "" FORCE)
set(OPENEXR_INSTALL OFF CACHE BOOL "" FORCE)
set(OPENEXR_INSTALL_TOOLS OFF CACHE BOOL "" FORCE)
# In-tree OpenEXR statically vendors its pinned libdeflate rather than
# linking whatever the host happens to have.
set(OPENEXR_FORCE_INTERNAL_DEFLATE ON CACHE BOOL "" FORCE)

# For each dep built in-tree, write a find_package() redirect declaring the
# package found with our pinned version. CMAKE_FIND_PACKAGE_REDIRECTS_DIR
# outranks every other search location (installed configs, CTL's bundled
# Find modules), so later find_package()/find_dependency() calls — OpenEXR
# looking for Imath, CTL looking for both — resolve to the in-tree targets
# instead of a system copy or the volatile build-tree export files (whose
# generate-time mtimes would keep ninja's regen perpetually dirty).
function(_ctlpy_redirect_find_package name version)
    string(REPLACE "." ";" _v "${version}")
    list(GET _v 0 _major)
    list(GET _v 1 _minor)
    list(GET _v 2 _patch)
    string(TOLOWER "${name}" _lc)
    # file(CONFIGURE), unlike file(WRITE), leaves the file untouched when
    # content is unchanged — rewriting these configure inputs every run
    # would keep build.ninja perpetually dirty.
    file(CONFIGURE OUTPUT "${CMAKE_FIND_PACKAGE_REDIRECTS_DIR}/${_lc}-config.cmake"
        @ONLY CONTENT
"# Generated by FindOrFetchCTL.cmake: ${name} is provided in-tree.
set(${name}_VERSION \"${version}\")
set(${name}_VERSION_MAJOR ${_major})
set(${name}_VERSION_MINOR ${_minor})
set(${name}_VERSION_PATCH ${_patch})
")
    file(CONFIGURE OUTPUT "${CMAKE_FIND_PACKAGE_REDIRECTS_DIR}/${_lc}-config-version.cmake"
        @ONLY CONTENT
"set(PACKAGE_VERSION \"${version}\")
set(PACKAGE_VERSION_COMPATIBLE TRUE)
")
endfunction()

# One dep at a time: each shim must exist before the NEXT dependency
# configures and goes looking for it.
FetchContent_MakeAvailable(Imath)
if(imath_SOURCE_DIR)
    _ctlpy_redirect_find_package(Imath ${_ctlpy_imath_version})
endif()
FetchContent_MakeAvailable(OpenEXR)
if(openexr_SOURCE_DIR)
    _ctlpy_redirect_find_package(OpenEXR ${_ctlpy_openexr_version})
endif()

# --- CTL --------------------------------------------------------------------
# To build against a local CTL checkout instead of the pinned tag, use
# FetchContent's stock override (no pre-built CTL libraries required):
#   pip install -e . -Ccmake.define.FETCHCONTENT_SOURCE_DIR_CTL=/path/to/CTL
set(CTL_GIT_TAG "ctl-1.5.5" CACHE STRING "Git tag/ref of CTL to fetch")
FetchContent_Declare(ctl
    GIT_REPOSITORY https://github.com/aces-aswf/CTL.git
    GIT_TAG        ${CTL_GIT_TAG}
    GIT_SHALLOW    TRUE
    SYSTEM           # CTL's warnings are not ours to fix
    EXCLUDE_FROM_ALL # build only what we link; skip CTL's install rules
    # CTL's bundled FindImath.cmake reads the LOCATION property, which is an
    # error on in-tree (non-imported) Imath targets. Removing it lets
    # find_package(Imath) fall through to CONFIG mode, which handles
    # installed and in-tree copies alike.
    PATCH_COMMAND ${CMAKE_COMMAND} -E rm -f cmake/modules/FindImath.cmake
)
set(CTL_BUILD_TESTS OFF CACHE BOOL "" FORCE)
option(CTL_BUILD_TOOLS "Build CTL command-line tools (ctlrender)" OFF)
FetchContent_MakeAvailable(ctl)

add_library(CTL::IlmCtl     ALIAS IlmCtl)
add_library(CTL::IlmCtlSimd ALIAS IlmCtlSimd)
add_library(CTL::IlmCtlMath ALIAS IlmCtlMath)
